# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/migrating-from-legacy/

dist: trusty
sudo: false
language: node_js

matrix:
  include:
    # AWS Lambda runtime version
    - node_js: 6.10

script:
  # Run linter
  - npm run lint

  # Run tests and gather code-coverage data
  - npm run cover

after_success:
  # send code-coverage data to Coveralls
  - cat ./coverage/lcov.info | node_modules/coveralls/bin/coveralls.js
