# Travis CI config
# http://docs.travis-ci.com/user/languages/javascript-with-nodejs/
# https://docs.travis-ci.com/user/customizing-the-build/
# https://docs.travis-ci.com/user/migrating-from-legacy/

language: node_js

node_js:
  - 6.10    # AWS Lambda runtime version

os:
  - linux
  - osx

  # FIXME: Travis-CI does not currently support secrets on Windows (i.e. AWS_SECRET_ACCESS_KEY)
  # https://github.com/travis-ci/travis-build/pull/1544
  # - windows

script: npm run lint && npm run coverage

after_success:
  # send code-coverage data to Coveralls
  - cat ./coverage/lcov.info | coveralls
